# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:23:06+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header
from starlette.requests import Request

from models import (
    BestPodcastsResponse,
    CuratedListFull,
    DeletePodcastResponse,
    EpisodeFull,
    EpisodeSimple,
    GetCuratedPodcastsResponse,
    GetEpisodeRecommendationsResponse,
    GetEpisodesInBatchResponse,
    GetGenresResponse,
    GetLanguagesResponse,
    GetPodcastRecommendationsResponse,
    GetPodcastsInBatchResponse,
    GetRegionsResponse,
    PlaylistResponse,
    PlaylistsResponse,
    PodcastAudienceResponse,
    PodcastFull,
    RelatedSearchesResponse,
    SafeMode,
    SearchResponse,
    ShowGenres,
    ShowPodcasts,
    Sort,
    Sort2,
    Sort4,
    Sort6,
    SortByDate,
    SpellCheckResponse,
    SubmitPodcastResponse,
    TopLevelOnly,
    TrendingSearchesResponse,
    Type1,
    Type4,
    TypeaheadResponse,
    UniquePodcasts,
)

app = MCPProxy(
    contact={
        'email': 'hello@listennotes.com',
        'name': 'Listen Notes',
        'url': 'https://www.listennotes.com/api/',
        'x-twitter': 'listennotes',
    },
    description='Simple & no-nonsense podcast search & directory API. Search all podcasts and episodes by people, places, or topics.\n',
    termsOfService='https://www.listennotes.com/api/terms/',
    title='Listen API: Podcast Search, Directory, and Insights API',
    version='2.0',
    servers=[
        {
            'description': 'API Production Server',
            'url': 'https://listen-api.listennotes.com/api/v2',
        }
    ],
)


@app.get(
    '/best_podcasts',
    description=""" Get a list of curated best podcasts by genre,
which are curated by Listen Notes staffs based on various signals from the Internet, e.g.,
top charts on other podcast platforms, recommendations from mainstream media,
user activities on listennotes.com...
You can get the genre ids from `GET /genres` endpoint.
This endpoint returns same data as https://www.listennotes.com/best-podcasts/
 """,
    tags=[
        'curated_podcast_listing',
        'podcast_discovery_recommendations',
        'podcast_genres_languages_info',
    ],
)
def get_best_podcasts(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    genre_id: Optional[str] = None,
    page: Optional[int] = None,
    region: Optional[str] = 'us',
    publisher_region: Optional[str] = None,
    language: Optional[str] = None,
    sort: Optional[Sort] = 'recent_added_first',
    safe_mode: Optional[SafeMode] = 0,
):
    """
    Fetch a list of best podcasts by genre
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/curated_podcasts',
    description=""" A bunch of curated lists from online media. For each list, you'll get basic info of up to 5 podcasts. To get detailed meta data of all podcasts in a specific list, you need to use `GET /curated_podcasts/{id}`. We add new curated lists to the database on a daily basis.
 """,
    tags=['curated_podcast_listing'],
)
def get_curated_podcasts(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    page: Optional[int] = 1,
):
    """
    Fetch curated lists of podcasts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/curated_podcasts/{id}',
    description=""" Get detailed meta data of all podcasts in a specific curated list.
This endpoint returns same data as https://www.listennotes.com/curated-podcasts/
 """,
    tags=['curated_podcast_listing', 'podcast_metadata_fetching'],
)
def get_curated_podcast_by_id(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'), id: str = ...
):
    """
    Fetch a curated list of podcasts by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/episodes',
    description=""" Batch fetch basic meta data for up to 10 episodes. This endpoint could be used to implement custom playlists for individual episodes. For detailed meta data of an individual episode, you need to use `GET /episodes/{id}`. This endpoint is available only in the PRO/ENTERPRISE plan.
 """,
    tags=['podcast_metadata_fetching'],
)
def get_episodes_in_batch(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    request: Request = ...,
):
    """
    Batch fetch basic meta data for episodes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/episodes/{id}',
    description=""" Fetch detailed meta data for a specific episode. """,
    tags=['podcast_metadata_fetching'],
)
def get_episode_by_id(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    id: str = ...,
    show_transcript: Optional[int] = 0,
):
    """
    Fetch detailed meta data for an episode by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/episodes/{id}/recommendations',
    description=""" Fetch up to 8 episode recommendations based on the given episode id. """,
    tags=['podcast_discovery_recommendations', 'podcast_metadata_fetching'],
)
def get_episode_recommendations(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    id: str = ...,
    safe_mode: Optional[SafeMode] = 0,
):
    """
    Fetch recommendations for an episode
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/genres',
    description=""" Get a list of podcast genres that are supported in Listen Notes.
The genre id can be passed to other endpoints as a parameter to get podcasts in a specific genre,
e.g., `GET /best_podcasts`, `GET /search`...
You may want to cache the list of genres on the client side.
 """,
    tags=['podcast_genres_languages_info'],
)
def get_genres(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    top_level_only: Optional[TopLevelOnly] = 0,
):
    """
    Fetch a list of podcast genres
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/just_listen',
    description=""" Recently published episodes are more likely to be fetched. Good luck! """,
    tags=['podcast_discovery_recommendations'],
)
def just_listen(x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key')):
    """
    Fetch a random podcast episode
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/languages',
    description=""" Get a list of languages that are supported in Listen Notes database. You can use the language string as query parameter in `GET /search`.
 """,
    tags=['podcast_genres_languages_info'],
)
def get_languages(x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key')):
    """
    Fetch a list of supported languages for podcasts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/playlists',
    description=""" This endpoint returns same data as listennotes.com/listen under your account.
You can use the **page** parameter to do pagination and fetch more playlists.
 """,
    tags=['user_playlist_operations'],
)
def get_playlists(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    sort: Optional[Sort2] = 'recent_added_first',
    page: Optional[int] = 1,
):
    """
    Fetch a list of your playlists.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/playlists/{id}',
    description=""" A playlist can be an episode list (i.e., all items are episodes) or a podcast list (i.e., all items are podcasts),
which is essentially the same as those created via listennotes.com/listen/.
This endpoint fetches a list of items (i.e., episodes or podcasts) in the playlist.
You can use the **last_pub_date_ms** parameter to do pagination and fetch more items.
A playlist can be **public** (discoverable on ListenNotes.com),
**unlisted** (accessible to anyone who knows the playlist id),
or **private** (accessible to its owner).
You can fetch all playlists created by you, and **public** / **unlisted** playlists created by others.
 """,
    tags=['podcast_metadata_fetching', 'user_playlist_operations'],
)
def get_playlist_by_id(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    id: str = ...,
    type: Optional[Type1] = 'episode_list',
    last_timestamp_ms: Optional[int] = 0,
    sort: Optional[Sort4] = 'recent_added_first',
):
    """
    Fetch a playlist's info and items (i.e., episodes or podcasts).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/podcasts',
    description=""" Batch fetch basic meta data for up to 10 podcasts.
This endpoint could be used to build something like OPML import,
allowing users to import a bunch of podcasts via rss urls.
For detailed meta data (including episodes) of an individual podcast, you need to use `GET /podcasts/{id}`. This endpoint is available only in the PRO/ENTERPRISE plan.
 """,
    tags=['podcast_metadata_fetching'],
)
def get_podcasts_in_batch(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    request: Request = ...,
):
    """
    Batch fetch basic meta data for podcasts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/podcasts/submit',
    description=""" Podcast hosting services can use this endpoint to help your users directly submit a new podcast to Listen Notes database. If the podcast doesn't exist in the database, "status" in the response will be "in review", and we'll review it within 12 hours. If the podcast exists, "status" in the response will be "found". If this submission is rejected, "status" in the response will be "rejected". You can use `POST /podcasts` to check if multiple podcasts exist in the database. If you want to get a notification once the podcast is accepted, you can either specify the "email" parameter or configure a webhook url in the dashboard: listennotes.com/api/dashboard/#webhooks
 """,
    tags=['podcast_submission_management'],
)
def submit_podcast(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    request: Request = ...,
):
    """
    Submit a podcast to Listen Notes database
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/podcasts/{id}',
    description=""" Podcast hosting services can use this endpoint to streamline the process of podcast deletion on behave of their users (podcasters). We will review the deletion request within 12 hours. If the podcast is already deleted, the "status" field in the response will be "deleted". Otherwise, the status field will be "in review". If you want to get a notification once the podcast is deleted, you can configure a webhook url in the dashboard: listennotes.com/api/dashboard/#webhooks
 """,
    tags=['podcast_submission_management'],
)
def delete_podcast_by_id(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    id: str = ...,
    reason: Optional[str] = None,
):
    """
    Request to delete a podcast
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/podcasts/{id}',
    description=""" Fetch detailed meta data and episodes for a specific podcast (up to 10 episodes each time).
You can use the **next_episode_pub_date** parameter to do pagination and fetch more episodes.
 """,
    tags=['podcast_metadata_fetching'],
)
def get_podcast_by_id(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    id: str = ...,
    next_episode_pub_date: Optional[int] = None,
    sort: Optional[Sort6] = 'recent_first',
):
    """
    Fetch detailed meta data and episodes for a podcast by id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/podcasts/{id}/audience',
    description=""" Fetch audience demographics for a podcast - 1) directly measured on the Listen Notes platform; 2) only supports audience breakdown by regions for now; 3) not every podcast has data. """,
    tags=['podcast_metadata_fetching', 'trending_search_data'],
)
def get_podcast_audience(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'), id: str = ...
):
    """
    Fetch audience demographics for a podcast
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/podcasts/{id}/recommendations',
    description=""" Fetch up to 8 podcast recommendations based on the given podcast id. """,
    tags=['podcast_discovery_recommendations'],
)
def get_podcast_recommendations(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    id: str = ...,
    safe_mode: Optional[SafeMode] = 0,
):
    """
    Fetch recommendations for a podcast
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/regions',
    description=""" It returns a dictionary of country codes (e.g., us, gb...) & country names (United States, United Kingdom...). The country code is used in the query parameter **region** of `GET /best_podcasts`.
 """,
    tags=['podcast_genres_languages_info', 'curated_podcast_listing'],
)
def get_regions(x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key')):
    """
    Fetch a list of supported countries/regions for best podcasts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/related_searches',
    description=""" Suggest related search terms. The results are more comprehensive than from `GET /typeahead`. This endpoint is available only in the PRO/ENTERPRISE plan. """,
    tags=['podcast_search_functions'],
)
def get_related_searches(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'), q: str = ...
):
    """
    Fetch related search terms
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/search',
    description=""" Full-text search on episodes, podcasts, or curated lists of podcasts.
Use the `offset` parameter to paginate through search results.
The FREE plan allows to see up to 30 search results (or `offset` < 30) per query.
The PRO plan allows to see up to 300 search results (or `offset` < 300) per query.
The ENTERPRISE plan allows to see up to 10,000 search results (or `offset` < 10000) per query.
 """,
    tags=['podcast_search_functions', 'podcast_discovery_recommendations'],
)
def search(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    q: str = ...,
    sort_by_date: Optional[SortByDate] = 0,
    type: Optional[Type4] = 'episode',
    offset: Optional[int] = 0,
    len_min: Optional[int] = 0,
    len_max: Optional[int] = None,
    episode_count_min: Optional[int] = None,
    episode_count_max: Optional[int] = None,
    update_freq_min: Optional[int] = None,
    update_freq_max: Optional[int] = None,
    genre_ids: Optional[str] = None,
    published_before: Optional[int] = None,
    published_after: Optional[int] = 0,
    only_in: Optional[str] = 'title,description,author,audio',
    language: Optional[str] = None,
    region: Optional[str] = None,
    ocid: Optional[str] = None,
    ncid: Optional[str] = None,
    safe_mode: Optional[SafeMode] = 0,
    unique_podcasts: Optional[UniquePodcasts] = 0,
):
    """
    Full-text search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/spellcheck',
    description=""" Suggest a list of words that correct the spelling errors of a search term. This endpoint is available only in the PRO/ENTERPRISE plan. """,
    tags=['podcast_search_functions'],
)
def spellcheck(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'), q: str = ...
):
    """
    Spell check on a search term
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/trending_searches',
    description=""" Fetch up to 10 most recent trending search terms on the Listen Notes platform. """,
    tags=['trending_search_data'],
)
def get_trending_searches(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key')
):
    """
    Fetch trending search terms
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/typeahead',
    description=""" Suggest search terms, podcast genres, and podcasts. """,
    tags=['podcast_search_functions'],
)
def typeahead(
    x__listen_a_p_i__key: str = Header(..., alias='X-ListenAPI-Key'),
    q: str = ...,
    show_podcasts: Optional[ShowPodcasts] = 0,
    show_genres: Optional[ShowGenres] = 0,
    safe_mode: Optional[SafeMode] = 0,
):
    """
    Typeahead search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
