# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:23:06+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class AudioField(RootModel[str]):
    root: str = Field(
        ...,
        description='Audio url of this episode, which can be played directly.',
        examples=['https://www.listennotes.com/e/p/11b34041e804491b9704d11f283c74de/'],
    )


class AudioLengthSecField(RootModel[int]):
    root: int = Field(
        ..., description='Audio length of this episode. In seconds.', examples=[567]
    )


class AvgAudioLengthSecField(RootModel[int]):
    root: int = Field(
        ...,
        description='Average audio length of all episodes of this podcast. In seconds.',
        examples=[1291],
    )


class BestPodcastsLNUrlField(RootModel[str]):
    root: str = Field(
        ...,
        description='Url of the list of best podcasts on [ListenNotes.com](https://www.ListenNotes.com).',
        examples=['https://www.listennotes.com/best-business-news-podcasts-95/'],
    )


class CountryField(RootModel[str]):
    root: str = Field(
        ...,
        description='The country where this podcast is produced.',
        examples=['United States'],
    )


class CuratedDescriptionField(RootModel[str]):
    root: str = Field(
        ...,
        description="This curated list's description.",
        examples=[
            'Commuting to work is always better when you have a great new podcast to listen to, and this year, we have discovered some of our favorite podcasts yet for readers and book-lovers. These podcasts for readers entertain us and provide no shortage of new book recommendations too.'
        ],
    )


class CuratedIdField(RootModel[str]):
    root: str = Field(
        ...,
        description='Curated list id, which can be used to further fetch detailed curated list metadata via `GET /curated_podcasts/{id}`.',
        examples=['Vb017Sx3l8F'],
    )


class CuratedLNUrlField(RootModel[str]):
    root: str = Field(
        ...,
        description='The url of this curated list on [ListenNotes.com](https://www.ListenNotes.com).',
        examples=[
            'https://www.listennotes.com/curated-podcasts/7-bookish-podcasts-for-avid-readers-on-H2r-TCWai8K/'
        ],
    )


class CuratedNameField(RootModel[str]):
    root: str = Field(
        ...,
        description='Curated list name.',
        examples=['7 Bookish Podcasts for Avid Readers On the Go'],
    )


class CuratedPubDateMsField(RootModel[int]):
    root: int = Field(
        ...,
        description='Published date of this curated list. In milliseconds.',
        examples=[1556843484301],
    )


class CuratedSourceDomainField(RootModel[str]):
    root: str = Field(
        ...,
        description='The domain name of the source of this curated list.',
        examples=['parade.com'],
    )


class CuratedSourceUrlField(RootModel[str]):
    root: str = Field(
        ...,
        description='Url of the source of this curated list.',
        examples=[
            'https://parade.com/718913/ashley_johnson/7-bookish-podcasts-for-avid-readers-on-the-go/'
        ],
    )


class CuratedTotalPodcastsField(RootModel[int]):
    root: int = Field(
        ...,
        description='The total number of podcasts in this curated list.',
        examples=[25],
    )


class CustomAudio(BaseModel):
    audio: Optional[str] = Field(
        None,
        description='Audio url, which can be played directly.',
        examples=['https://example.com/audio.mp3'],
    )
    audio_length_sec: Optional[int] = Field(
        None, description='Audio length in seconds.', examples=[253]
    )
    image: Optional[str] = Field(
        None,
        description='High resolution image url of this custom audio.',
        examples=[
            'https://cdn-images-1.listennotes.com/playlist/image/6907e8ff6b6c45df94cc059753f369cc.JPEG'
        ],
    )
    pub_date_ms: Optional[int] = Field(
        None,
        description="Published date (in milliseconds) of this custom audio.\nFor now, it's the same as **added_at_ms** of this playlist item.\n",
        examples=[1595567028133],
    )
    thumbnail: Optional[str] = Field(
        None,
        description='Low resolution image url of this custom audio.',
        examples=[
            'https://d3sv2eduhewoas.cloudfront.net/playlist/image/48477deae02649d7ab9d3f1b3966af38.JPEG'
        ],
    )
    title: Optional[str] = Field(
        None,
        description='Custom audio title.',
        examples=['An awesome audio to listen.'],
    )


class Status(Enum):
    deleted = 'deleted'
    in_review = 'in review'


class DeletePodcastResponse(BaseModel):
    status: Status = Field(
        ...,
        description='The status of this podcast deletion request.',
        examples=['deleted'],
    )


class DeletedItem(BaseModel):
    error: Optional[str] = Field(
        None,
        description='Why this episode or podcast is deleted?',
        examples=['This episode is deleted from the podcast database, because...'],
    )
    id: Optional[str] = Field(
        None,
        description='Episode id or podcast id.',
        examples=['96fc400171364e32897b25d84a8ed8ec'],
    )
    status: Optional[str] = Field(
        None,
        description='The status of this episode or podcast. For now, the only possible value is **deleted**.',
        examples=['deleted'],
    )
    title: Optional[str] = Field(
        None,
        description='Episode title or podcast title.',
        examples=['This is a test episode'],
    )


class EarliestPubDateMsField(RootModel[int]):
    root: int = Field(
        ...,
        description='The published date of the oldest episode of this podcast. In milliseconds',
        examples=[1470667902000],
    )


class EmailField(RootModel[str]):
    root: str = Field(
        ...,
        description="The email of this podcast's producer. This field is available only in the PRO/ENTERPRISE plan.",
        examples=['hello@example.com'],
    )


class EpisodeDescriptionField(RootModel[str]):
    root: str = Field(
        ...,
        description="Html of this episode's full description",
        examples=[
            '<p>Disney chief Bob Iger shared news about Star Wars movies in 2020 and beyond, but some media outlets gave conflicting reports about it. Here\'s the real scoop. Punch it!</p> <p>***We’re listener supported! Go to http://Patreon.com/sw7x7 to donate to the Star Wars 7x7 podcast, and you’ll get some fabulous rewards for your pledge.***\xa0</p> <p>Check out SW7x7.com for full Star Wars 7x7 show notes and links, and to comment on any of the content of this episode! If you like what you\'ve heard, please leave us a rating or review on iTunes or Stitcher, which will also help more people discover this Star Wars podcast.</p> <p>Don\'t forget to join the Star Wars 7x7 fun on Facebook at Facebook.com/SW7x7, and follow the breaking news Twitter feed at Twitter.com/SW7x7Podcast. We\'re also on Pinterest and Instagram as "SW7x7" too, and we\'d love to connect with you there!</p>\n'
        ],
    )


class EpisodeIdField(RootModel[str]):
    root: str = Field(
        ...,
        description='Episode id, which can be used to further fetch detailed episode metadata via `GET /episodes/{id}`.',
        examples=['4d82e50314174754a3b603912448e812'],
    )


class EpisodeImageField(RootModel[str]):
    root: str = Field(
        ...,
        description="Image url for this episode.\nIf an episode doesn't have its own image, then this field would be the url of the podcast artwork image.\nIf you are using PRO/ENTERPRISE plan, then it's\na high resolution image (1400x1400). If you are using FREE plan, then it's the same as **thumbnail**,\nlow resolution image (300x300).\n",
        examples=[
            'https://cdn-images-1.listennotes.com/podcasts/exponent-ben-thompson-james-allworth-OaJSjb4xQv3.1400x1400.jpg'
        ],
    )


class EpisodeLNEditUrlField(RootModel[str]):
    root: str = Field(
        ...,
        description='Edit url of this episode where you can update the audio url if you find the audio is broken.',
        examples=[
            'https://www.listennotes.com/e/11b34041e804491b9704d11f283c74de/#edit'
        ],
    )


class EpisodeLNUrlField(RootModel[str]):
    root: str = Field(
        ...,
        description='The url of this episode on [ListenNotes.com](https://www.ListenNotes.com).',
        examples=['https://www.listennotes.com/e/4d82e50314174754a3b603912448e812/'],
    )


class EpisodeNameField(RootModel[str]):
    root: str = Field(
        ...,
        description='Episode name.',
        examples=[
            'Celebration Recap, Jason Fry and Christian Blauvelt Interviews – SWBW #101'
        ],
    )


class EpisodePubDateMsField(RootModel[int]):
    root: int = Field(
        ...,
        description='Published date for this episode. In millisecond.',
        examples=[1474873200000],
    )


class EpisodeThumbnailField(RootModel[str]):
    root: str = Field(
        ...,
        description="Thumbnail image (300x300) url for this episode.\nIf an episode doesn't have its own image, then this field would be the url of the podcast artwork thumbnail image.\n",
        examples=[
            'https://cdn-images-1.listennotes.com/podcasts/exponent-ben-thompson-james-allworth-OaJSjb4xQv3.300x300.jpg'
        ],
    )


class ExplicitField(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Whether this podcast contains explicit language.',
        examples=[False],
    )


class Genre(BaseModel):
    id: Optional[int] = Field(None, description='Genre id', examples=[93])
    name: Optional[str] = Field(None, description='Genre name.', examples=['Business'])
    parent_id: Optional[int] = Field(
        None, description='Parent genre id.', examples=[95]
    )


class GenreIdsField(RootModel[List[int]]):
    root: List[int] = Field(..., examples=[[138, 86, 160, 68, 82, 100, 101]])


class GetEpisodesInBatchForm(BaseModel):
    ids: str = Field(
        ...,
        description='Comma-separated list of episode ids.',
        examples=['c577d55b2b2b483c969fae3ceb58e362,0f34a9099579490993eec9e8c8cebb82'],
    )


class GetGenresResponse(BaseModel):
    genres: List[Genre]


class GetLanguagesResponse(BaseModel):
    languages: List[str] = Field(
        ...,
        examples=[
            [
                'Any language',
                'Afar',
                'Abkhazian',
                'Afrikaans',
                'Akan',
                'Albanian',
                'Arabic',
                'Azerbaijani',
                'Bambara',
                'Bashkir',
                'Basque',
                'Belarusian',
                'Bulgarian',
                'Catalan',
                'Chamorro',
                'Chinese',
                'Croatian',
                'Czech',
                'Danish',
                'Dutch',
                'English',
                'Estonian',
                'Faeroese',
                'Finnish',
                'French',
                'Gaelic',
                'Galician',
                'German',
                'Greek',
            ]
        ],
    )


class ShowLatestEpisodes(Enum):
    integer_0 = 0
    integer_1 = 1


class GetPodcastsInBatchForm(BaseModel):
    ids: Optional[str] = Field(
        None,
        description='Comma-separated list of podcast ids.',
        examples=[
            '3302bc71139541baa46ecb27dbf6071a,68faf62be97149c280ebcc25178aa731,37589a3e121e40debe4cef3d9638932a,9cf19c590ff0484d97b18b329fed0c6a'
        ],
    )
    itunes_ids: Optional[str] = Field(
        None,
        description='Comma-separated Apple Podcasts (iTunes) ids, e.g., 659155419',
        examples=['1457514703,1386234384,659155419'],
    )
    next_episode_pub_date: Optional[int] = Field(
        None,
        description="For latest episodes pagination. It's the value of **next_episode_pub_date** from the response of last request. If not specified, just return latest 15 episodes.\n",
        examples=[1557394247000],
    )
    rsses: Optional[str] = Field(
        None,
        description='Comma-separated rss urls.',
        examples=[
            'https://rss.art19.com/recode-decode,https://rss.art19.com/the-daily,https://www.npr.org/rss/podcast.php?id=510331,https://www.npr.org/rss/podcast.php?id=510331'
        ],
    )
    show_latest_episodes: Optional[ShowLatestEpisodes] = Field(
        0,
        description='Whether or not to fetch up to 15 latest episodes from these podcasts, sorted by pub_date. 1 is yes, and 0 is no.\n',
        examples=[1],
    )
    spotify_ids: Optional[str] = Field(
        None,
        description='Comma-separated Spotify ids, e.g., 3DDfEsKDIDrTlnPOiG4ZF4',
        examples=[
            '3DDfEsKDIDrTlnPOiG4ZF4,4qDNe5Gvl1XxdLinUGEXrC,23NZCM4ik6o3UYkM473Itz'
        ],
    )


class GetRegionsResponse(BaseModel):
    regions: Dict[str, Any] = Field(
        ...,
        examples=[
            {'au': 'Australia', 'de': 'Germany', 'ua': 'Ukraine', 'us': 'United States'}
        ],
    )


class ImageField(RootModel[str]):
    root: str = Field(
        ...,
        description="Image url for this podcast's artwork. If you are using PRO/ENTERPRISE plan, then it's\na high resolution image (1400x1400). If you are using FREE plan, then it's the same as **thumbnail**,\nlow resolution image (300x300).\n",
        examples=[
            'https://cdn-images-1.listennotes.com/podcasts/exponent-ben-thompson-james-allworth-OaJSjb4xQv3.1400x1400.jpg'
        ],
    )


class IsClaimedField(RootModel[bool]):
    root: bool = Field(
        ...,
        description='Whether this podcast is claimed by its producer on [ListenNotes.com](https://www.ListenNotes.com).',
        examples=[True],
    )


class LanguageField(RootModel[str]):
    root: str = Field(
        ...,
        description='The language of this podcast. You can get all supported languages from `GET /languages`.',
        examples=['English'],
    )


class LatestEpisodeIdField(RootModel[str]):
    root: str = Field(
        ...,
        description='The id of the most recently published episode of this podcast, which can be used to further fetch detailed episode metadata via `GET /episodes/{id}`.',
        examples=['d057092e57cc4ced80e0efaa196593d9'],
    )


class LatestPubDateMsField(RootModel[int]):
    root: int = Field(
        ...,
        description='The published date of the latest episode of this podcast. In milliseconds',
        examples=[1557499770000],
    )


class LinkField(RootModel[str]):
    root: str = Field(
        ...,
        description='Web link of this episode.',
        examples=['https://www.npr.org/2020/01/22/798532179/soleimanis-iran'],
    )


class ListenScoreField(RootModel[int]):
    root: int = Field(
        ...,
        description="The estimated popularity score of a podcast compared to all other rss-based public podcasts in the world on a scale from 0 to 100.\nIf the score is not available, it'll be null. Learn more at listennotes.com/listen-score\n",
        examples=[81],
    )


class ListenScoreGlobalRankField(RootModel[str]):
    root: str = Field(
        ...,
        description="The estimated popularity ranking of a podcast compared to all other rss-based public podcasts in the world.\nFor example, if the value is 0.5%, then this podcast is one of the top 0.5% most popular shows out of all podcasts globally, ranked by Listen Score.\nIf the ranking is not available, it'll be null. Learn more at listennotes.com/listen-score\n",
        examples=['0.5%'],
    )


class MaybeAudioInvalidField(RootModel[bool]):
    root: bool = Field(
        ...,
        description="Whether or not this episode's audio is invalid. Podcasters may delete the original audio.",
        examples=[False],
    )


class NextEpisodePubDateField(RootModel[int]):
    root: int = Field(
        ...,
        description='Passed to the **next_episode_pub_date** parameter of `GET /podcasts/{id}` to paginate through episodes of that podcast.',
        examples=[1470667902000],
    )


class PlaylistDescriptionField(RootModel[str]):
    root: str = Field(
        ...,
        description='Playlist description.',
        examples=['A curated playlist of podcasts about podcasting.'],
    )


class PlaylistIdField(RootModel[str]):
    root: str = Field(
        ...,
        description='A 11-character playlist id, which can be used to further fetch detailed playlist metadata via `GET /playlists/{id}`.',
        examples=['m1pe7z60bsw'],
    )


class PlaylistImageField(RootModel[str]):
    root: str = Field(
        ...,
        description='High resolution image url of the playlist.',
        examples=[
            'https://cdn-images-1.listennotes.com/playlist/image/6907e8ff6b6c45df94cc059753f369cc.JPEG'
        ],
    )


class Type(Enum):
    episode = 'episode'
    custom_audio = 'custom_audio'
    podcast = 'podcast'


class PlaylistLastTimestampMsField(RootModel[int]):
    root: int = Field(
        ...,
        description='Passed to the **last_timestamp_ms** parameter of `GET /playlists/{id}` to paginate through items of that playlist.\n',
        examples=[1595641092907],
    )


class PlaylistListennotesUrlField(RootModel[str]):
    root: str = Field(
        ...,
        description='The url of this playlist on ListenNotes.com.',
        examples=[
            'https://www.listennotes.com/listen/podcasts-about-podcasting-m1pe7z60bsw/?display=episode'
        ],
    )


class PlaylistNameField(RootModel[str]):
    root: str = Field(
        ..., description='Playlist name.', examples=['My podcast playlist']
    )


class Type1(Enum):
    episode_list = 'episode_list'
    podcast_list = 'podcast_list'


class PlaylistThumbnailField(RootModel[str]):
    root: str = Field(
        ...,
        description='Low resolution image url of the playlist.',
        examples=[
            'https://d3sv2eduhewoas.cloudfront.net/playlist/image/48477deae02649d7ab9d3f1b3966af38.JPEG'
        ],
    )


class PlaylistVisibilityField(Enum):
    public = 'public'
    unlisted = 'unlisted'
    private = 'private'


class Playlist(BaseModel):
    description: Optional[PlaylistDescriptionField] = None
    episode_count: Optional[int] = Field(
        None,
        description='The number of episodes (including custom audio) in this playlist.',
        examples=[23],
    )
    id: Optional[PlaylistIdField] = None
    image: Optional[PlaylistImageField] = None
    last_timestamp_ms: Optional[PlaylistLastTimestampMsField] = None
    listennotes_url: Optional[PlaylistListennotesUrlField] = None
    name: Optional[PlaylistNameField] = None
    podcast_count: Optional[int] = Field(
        None, description='The number of podcasts in this playlist.', examples=[10]
    )
    thumbnail: Optional[PlaylistThumbnailField] = None
    total_audio_length_sec: Optional[int] = Field(
        None,
        description='Total audio length of all episodes in this playlist, in seconds.',
        examples=[234567],
    )
    visibility: Optional[PlaylistVisibilityField] = None


class PlaylistsResponse(BaseModel):
    has_next: Optional[bool] = Field(None, examples=[True])
    has_previous: Optional[bool] = Field(None, examples=[True])
    next_page_number: Optional[int] = Field(None, examples=[3])
    page_number: Optional[int] = Field(None, examples=[2])
    playlists: Optional[List[Playlist]] = None
    previous_page_number: Optional[int] = Field(None, examples=[1])
    total: Optional[int] = Field(None, examples=[325])


class ByRegion(BaseModel):
    ratio: Optional[str] = Field(
        None,
        description='percentage of audience from this specific region',
        examples=['20.22%'],
    )
    region: Optional[str] = Field(
        None, description='2-letter country code of a region.', examples=['us']
    )


class PodcastAudienceResponse(BaseModel):
    by_regions: Optional[List[ByRegion]] = None


class PodcastDescriptionField(RootModel[str]):
    root: str = Field(
        ...,
        description="Html of this episode's full description",
        examples=[
            "<p>The Star Wars 7x7 Podcast is Rebel-rousing fun for everyday Jedi, between 7 and 14 minutes a day, 7 days a week. Join host Allen Voivod for Star Wars news, history, interviews, trivia, and deep dives into the Star Wars story as told in movies, books, comics, games, cartoons, and more. Subscribe now for your daily dose of Star Wars joy. It's destiny unleashed!</p>"
        ],
    )


class PodcastExtraField(BaseModel):
    amazon_music_url: Optional[str] = Field(
        None,
        description='Amazon Music url for this podcast',
        examples=[
            'https://music.amazon.com/podcasts/6fc6d683-9ef3-4850-9c35-8e8b1a42a147/the-lock-sportscast'
        ],
    )
    facebook_handle: Optional[str] = Field(
        None,
        description='Facebook username affiliated with this podcast',
        examples=['sw7x7'],
    )
    google_url: Optional[str] = Field(
        None,
        description='Google Podcasts url for this podcast',
        examples=[
            'https://podcasts.google.com/feed/aHR0cHM6Ly9yc3MuYXJ0MTkuY29tL2pvaG4tc29sb21vbi1yZXBvcnRz'
        ],
    )
    instagram_handle: Optional[str] = Field(
        None,
        description='Instagram username affiliated with this podcast',
        examples=['sw7x7'],
    )
    linkedin_url: Optional[str] = Field(
        None, description='LinkedIn url affiliated with this podcast'
    )
    patreon_handle: Optional[str] = Field(
        None,
        description='Patreon username affiliated with this podcast',
        examples=['sw7x7'],
    )
    spotify_url: Optional[str] = Field(
        None,
        description='Spotify url for this podcast',
        examples=['https://open.spotify.com/show/2rQJUP9Y3HxemiW3JHt9WV'],
    )
    twitter_handle: Optional[str] = Field(
        None,
        description='Twitter username affiliated with this podcast',
        examples=['SW7x7podcast'],
    )
    url1: Optional[str] = Field(None, description='Url affiliated with this podcast')
    url2: Optional[str] = Field(None, description='Url affiliated with this podcast')
    url3: Optional[str] = Field(None, description='Url affiliated with this podcast')
    wechat_handle: Optional[str] = Field(
        None, description='WeChat username affiliated with this podcast'
    )
    youtube_url: Optional[str] = Field(
        None,
        description='YouTube url affiliated with this podcast',
        examples=['https://www.youtube.com/sw7x7'],
    )


class PodcastIdField(RootModel[str]):
    root: str = Field(
        ...,
        description='Podcast id, which can be used to further fetch detailed podcast metadata via `GET /podcasts/{id}`.',
        examples=['4d3fe717742d4963a85562e9f84d8c79'],
    )


class PodcastLNUrlField(RootModel[str]):
    root: str = Field(
        ...,
        description='The url of this podcast on [ListenNotes.com](https://www.ListenNotes.com).',
        examples=['https://www.listennotes.com/c/4d3fe717742d4963a85562e9f84d8c79/'],
    )


class PodcastLookingForField(BaseModel):
    cohosts: Optional[bool] = Field(
        None,
        description='Whether this podcast is looking for cohosts.',
        examples=[True],
    )
    cross_promotion: Optional[bool] = Field(
        None,
        description='Whether this podcast is looking for cross promotion opportunities with other podcasts.',
        examples=[True],
    )
    guests: Optional[bool] = Field(
        None, description='Whether this podcast is looking for guests.', examples=[True]
    )
    sponsors: Optional[bool] = Field(
        None,
        description='Whether this podcast is looking for sponsors.',
        examples=[True],
    )


class PodcastNameField(RootModel[str]):
    root: str = Field(
        ...,
        description='Podcast name.',
        examples=['Star Wars 7x7 | Star Wars News, Interviews, and More!'],
    )


class PodcastTitleHighlightedField(RootModel[str]):
    root: str = Field(
        ...,
        description='Highlighted segment of podcast name.',
        examples=[
            '<span class=\\"ln-search-highlight\\">Star</span> <span class=\\"ln-search-highlight\\">Wars</span> 7x7 | <span class=\\"ln-search-highlight\\">Star</span> <span class=\\"ln-search-highlight\\">Wars</span> News, Interviews, and More!'
        ],
    )


class PodcastTitleOriginalField(RootModel[str]):
    root: str = Field(
        ...,
        description='Plain text of podcast name.',
        examples=['Star Wars 7x7 | Star Wars News, Interviews, and More!'],
    )


class PodcastTypeField(Enum):
    episodic = 'episodic'
    serial = 'serial'


class PublisherField(RootModel[str]):
    root: str = Field(
        ..., description='Podcast publisher name.', examples=['Planet Broadcasting']
    )


class PublisherHighlightedField(RootModel[str]):
    root: str = Field(
        ...,
        description="Highlighted segment of this podcast's publisher name.",
        examples=[
            '<span class=\\"ln-search-highlight\\">Star</span> <span class=\\"ln-search-highlight\\">Wars</span> Daily, by Allen Voivod'
        ],
    )


class PublisherOriginalField(RootModel[str]):
    root: str = Field(
        ...,
        description="Plain text of this podcast's publisher name.",
        examples=['Star Wars Daily, by Allen Voivod'],
    )


class RelatedSearchesResponse(BaseModel):
    terms: List[str] = Field(
        ...,
        description='Related search terms',
        examples=[
            [
                'evergrande stock',
                'evergrande china',
                'evergrande group',
                'evergrande news',
            ]
        ],
    )


class RssField(RootModel[str]):
    root: str = Field(
        ...,
        description='RSS url of this podcast. This field is available only in the PRO/ENTERPRISE plan.',
        examples=['https://sw7x7.libsyn.com/rss'],
    )


class Token(BaseModel):
    offset: Optional[int] = Field(
        None,
        description='The zero-based offset from the beginning of the text query string to the word that is misspelled',
        examples=[5],
    )
    suggestion: Optional[str] = Field(
        None,
        description='A word that corrects the spelling error',
        examples=['evergrande'],
    )
    token: Optional[str] = Field(
        None, description='The misspelled word', examples=['evergrand']
    )


class SpellCheckResponse(BaseModel):
    corrected_text_html: str = Field(
        ...,
        description='The corrected text for the entire search term (multiple words/tokens), where misspelled tokens are replaced with the correct texts and html tags <b><i>',
        examples=['<b><i>evergrande</i></b> stock'],
    )
    tokens: List[Token] = Field(
        ...,
        description='The word in the text query string that is not spelled correctly',
    )


class SubmitPodcastForm(BaseModel):
    email: Optional[str] = Field(
        None,
        description="A valid email address. If **email** is specified, then we'll notify this email address once the podcast is accepted.",
        examples=['hello@example.com'],
    )
    rss: str = Field(
        ...,
        description='A valid podcast rss url.',
        examples=['https://feeds.megaphone.fm/committed'],
    )


class Status1(Enum):
    found = 'found'
    in_review = 'in review'
    rejected = 'rejected'


class ThumbnailField(RootModel[str]):
    root: str = Field(
        ...,
        description="Thumbnail image url for this podcast's artwork (300x300).",
        examples=[
            'https://cdn-images-1.listennotes.com/podcasts/exponent-ben-thompson-james-allworth-OaJSjb4xQv3.300x300.jpg'
        ],
    )


class TotalEpisodesField(RootModel[int]):
    root: int = Field(
        ..., description='Total number of episodes in this podcast.', examples=[324]
    )


class TranscriptField(RootModel[str]):
    root: str = Field(
        ...,
        description="The transcript of this episode, in plain text (with the newline character \\n). If there's not transcript, it is null. This field is available only in the PRO/ENTERPRISE plan.",
        examples=['00:00:07 Welcome to this podcast...\n'],
    )


class TrendingSearchesResponse(BaseModel):
    terms: List[str] = Field(
        ...,
        description='Trending search terms',
        examples=[['Taliban', 'Andrew Cuomo', 'john McAfee']],
    )


class UpdateFrequencyHoursField(RootModel[int]):
    root: int = Field(
        ...,
        description="How frequently does this podcast release a new episode? In hours. For example, if the value is 166, then it's every 166 hours (or weekly).",
        examples=[168],
    )


class WebsiteField(RootModel[str]):
    root: str = Field(
        ..., description='Website url of this podcast.', examples=['http://sw7x7.com/']
    )


class ITunesIdField(RootModel[int]):
    root: int = Field(
        ..., description='iTunes id for this podcast.', examples=[896354638]
    )


class Sort(Enum):
    recent_added_first = 'recent_added_first'
    oldest_added_first = 'oldest_added_first'
    recent_published_first = 'recent_published_first'
    oldest_published_first = 'oldest_published_first'
    listen_score = 'listen_score'


class SafeMode(Enum):
    integer_0 = 0
    integer_1 = 1


class TopLevelOnly(Enum):
    integer_0 = 0
    integer_1 = 1


class Sort2(Enum):
    recent_added_first = 'recent_added_first'
    oldest_added_first = 'oldest_added_first'
    name_a_to_z = 'name_a_to_z'
    name_z_to_a = 'name_z_to_a'


class Sort4(Enum):
    recent_added_first = 'recent_added_first'
    oldest_added_first = 'oldest_added_first'
    recent_published_first = 'recent_published_first'
    oldest_published_first = 'oldest_published_first'


class Sort6(Enum):
    recent_first = 'recent_first'
    oldest_first = 'oldest_first'


class SortByDate(Enum):
    integer_0 = 0
    integer_1 = 1


class Type4(Enum):
    episode = 'episode'
    podcast = 'podcast'
    curated = 'curated'


class UniquePodcasts(Enum):
    integer_0 = 0
    integer_1 = 1


class ShowPodcasts(Enum):
    integer_0 = 0
    integer_1 = 1


class ShowGenres(Enum):
    integer_0 = 0
    integer_1 = 1


class EpisodeMinimum(BaseModel):
    audio: Optional[AudioField] = None
    audio_length_sec: Optional[AudioLengthSecField] = None
    description: Optional[EpisodeDescriptionField] = None
    explicit_content: Optional[ExplicitField] = None
    id: Optional[EpisodeIdField] = None
    image: Optional[ImageField] = None
    link: Optional[LinkField] = None
    listennotes_edit_url: Optional[EpisodeLNEditUrlField] = None
    listennotes_url: Optional[EpisodeLNUrlField] = None
    maybe_audio_invalid: Optional[MaybeAudioInvalidField] = None
    pub_date_ms: Optional[EpisodePubDateMsField] = None
    thumbnail: Optional[ThumbnailField] = None
    title: Optional[EpisodeNameField] = None


class Podcast(BaseModel):
    genre_ids: Optional[GenreIdsField] = None
    id: Optional[PodcastIdField] = None
    image: Optional[ImageField] = None
    listen_score: Optional[ListenScoreField] = None
    listen_score_global_rank: Optional[ListenScoreGlobalRankField] = None
    listennotes_url: Optional[PodcastLNUrlField] = None
    publisher_highlighted: Optional[PublisherHighlightedField] = None
    publisher_original: Optional[PublisherOriginalField] = None
    thumbnail: Optional[ThumbnailField] = None
    title_highlighted: Optional[PodcastTitleHighlightedField] = None
    title_original: Optional[PodcastTitleOriginalField] = None


class EpisodeSearchResult(BaseModel):
    audio: Optional[AudioField] = None
    audio_length_sec: Optional[AudioLengthSecField] = None
    description_highlighted: Optional[str] = Field(
        None,
        description="Highlighted segment of this episode's description",
        examples=[
            '...Go to http://Patreon.com/sw7x7 to donate to the <span class="ln-search-highlight">Star</span> <span class="ln-search-highlight">Wars</span> 7x7 podcast, and you\'ll get some fabulous rewards for your pledge.***  Check out SW7x7.com for full <span class="ln-search-highlight">Star</span> <span class="ln-search-highlight">Wars</span> 7x7 show notes and links, and to\n'
        ],
    )
    description_original: Optional[str] = Field(
        None,
        description="Plain text of this episode's description",
        examples=[
            'Yeah, Star Wars Celebration Orlando is 32 days away, but what\'s the scoop on Celebration 2018? Plus, Rebels Day is Saturday, and much more in our update. Punch it! ***We\'re listener supported! Go to http://Patreon.com/sw7x7 to donate to the Star Wars 7x7 podcast, and youâ€™ll get some fabulous rewards for your pledge.***  Check out SW7x7.com for full Star Wars 7x7 show notes and links, and to comment on any of the content of this episode! If you like what you\'ve heard, please leave us a rating or review on iTunes or Stitcher, which will also help more people discover this Star Wars podcast. Don\'t forget to join the Star Wars 7x7 fun on Facebook at Facebook.com/SW7x7, and follow the breaking news Twitter feed at Twitter.com/SW7x7Podcast. We\'re also on Pinterest and Instagram as "SW7x7" too, and we\'d love to connect with you there!\n'
        ],
    )
    explicit_content: Optional[ExplicitField] = None
    id: Optional[EpisodeIdField] = None
    image: Optional[EpisodeImageField] = None
    itunes_id: Optional[ITunesIdField] = None
    link: Optional[LinkField] = None
    listennotes_url: Optional[EpisodeLNUrlField] = None
    podcast: Optional[Podcast] = Field(
        None, description='The podcast that this episode belongs to.'
    )
    pub_date_ms: Optional[EpisodePubDateMsField] = None
    rss: Optional[RssField] = None
    thumbnail: Optional[EpisodeThumbnailField] = None
    title_highlighted: Optional[str] = Field(
        None,
        description="Highlighted segment of this episode's title",
        examples=[
            '815: <span class="ln-search-highlight">Star</span> <span class="ln-search-highlight">Wars</span> 2020 Movie and Beyond!'
        ],
    )
    title_original: Optional[str] = Field(
        None,
        description="Plain text of this episode' title",
        examples=['815: Star Wars 2020 Movie and Beyond!'],
    )
    transcripts_highlighted: Optional[List[str]] = Field(
        None,
        description='Up to 2 highlighted segments of the audio transcript of this episode.',
    )


class PodcastFull(BaseModel):
    audio_length_sec: Optional[AvgAudioLengthSecField] = None
    country: Optional[CountryField] = None
    description: Optional[PodcastDescriptionField] = None
    earliest_pub_date_ms: Optional[EarliestPubDateMsField] = None
    email: Optional[EmailField] = None
    episodes: Optional[List[EpisodeMinimum]] = None
    explicit_content: Optional[ExplicitField] = None
    extra: Optional[PodcastExtraField] = None
    genre_ids: Optional[GenreIdsField] = None
    id: Optional[PodcastIdField] = None
    image: Optional[ImageField] = None
    is_claimed: Optional[IsClaimedField] = None
    itunes_id: Optional[ITunesIdField] = None
    language: Optional[LanguageField] = None
    latest_episode_id: Optional[LatestEpisodeIdField] = None
    latest_pub_date_ms: Optional[LatestPubDateMsField] = None
    listen_score: Optional[ListenScoreField] = None
    listen_score_global_rank: Optional[ListenScoreGlobalRankField] = None
    listennotes_url: Optional[PodcastLNUrlField] = None
    looking_for: Optional[PodcastLookingForField] = None
    next_episode_pub_date: Optional[NextEpisodePubDateField] = None
    publisher: Optional[PublisherField] = None
    rss: Optional[RssField] = None
    thumbnail: Optional[ThumbnailField] = None
    title: Optional[PodcastNameField] = None
    total_episodes: Optional[TotalEpisodesField] = None
    type: Optional[PodcastTypeField] = None
    update_frequency_hours: Optional[UpdateFrequencyHoursField] = None
    website: Optional[WebsiteField] = None


class PodcastMinimum(BaseModel):
    id: Optional[PodcastIdField] = None
    image: Optional[ImageField] = None
    listen_score: Optional[ListenScoreField] = None
    listen_score_global_rank: Optional[ListenScoreGlobalRankField] = None
    listennotes_url: Optional[PodcastLNUrlField] = None
    publisher: Optional[PublisherField] = None
    thumbnail: Optional[ThumbnailField] = None
    title: Optional[PodcastNameField] = None


class PodcastMinimumRss(BaseModel):
    id: Optional[PodcastIdField] = None
    image: Optional[ImageField] = None
    listennotes_url: Optional[PodcastLNUrlField] = None
    publisher: Optional[PublisherField] = None
    rss: Optional[RssField] = None
    thumbnail: Optional[ThumbnailField] = None
    title: Optional[PodcastNameField] = None


class PodcastSearchResult(BaseModel):
    audio_length_sec: Optional[AvgAudioLengthSecField] = None
    description_highlighted: Optional[str] = Field(
        None,
        description='Highlighted segment of podcast description',
        examples=[
            '...Join host Allen Voivod for <span class="ln-search-highlight">Star</span> <span class="ln-search-highlight">Wars</span> news, history, interviews, trivia, and deep dives into the <span class="ln-search-highlight">Star</span> <span class="ln-search-highlight">Wars</span> story as told in movies, books, comics, games, cartoons, and more.\n'
        ],
    )
    description_original: Optional[str] = Field(
        None,
        description='Plain text of podcast description',
        examples=[
            "The Star Wars 7x7 Podcast is Rebel-rousing fun for everyday Jedi, between 7 and 14 minutes a day, 7 days a week. Join host Allen Voivod for Star Wars news, history, interviews, trivia, and deep dives into the Star Wars story as told in movies, books, comics, games, cartoons, and more. Subscribe now for your daily dose of Star Wars joy. It's destiny unleashed! #SW7x7\n"
        ],
    )
    earliest_pub_date_ms: Optional[EarliestPubDateMsField] = None
    email: Optional[EmailField] = None
    explicit_content: Optional[ExplicitField] = None
    genre_ids: Optional[GenreIdsField] = None
    id: Optional[PodcastIdField] = None
    image: Optional[ImageField] = None
    itunes_id: Optional[ITunesIdField] = None
    latest_episode_id: Optional[LatestEpisodeIdField] = None
    latest_pub_date_ms: Optional[LatestPubDateMsField] = None
    listen_score: Optional[ListenScoreField] = None
    listen_score_global_rank: Optional[ListenScoreGlobalRankField] = None
    listennotes_url: Optional[PodcastLNUrlField] = None
    publisher_highlighted: Optional[PublisherHighlightedField] = None
    publisher_original: Optional[PublisherOriginalField] = None
    rss: Optional[RssField] = None
    thumbnail: Optional[ThumbnailField] = None
    title_highlighted: Optional[PodcastTitleHighlightedField] = None
    title_original: Optional[PodcastTitleOriginalField] = None
    total_episodes: Optional[TotalEpisodesField] = None
    update_frequency_hours: Optional[UpdateFrequencyHoursField] = None
    website: Optional[WebsiteField] = None


class PodcastSimple(BaseModel):
    audio_length_sec: Optional[AvgAudioLengthSecField] = None
    country: Optional[CountryField] = None
    description: Optional[PodcastDescriptionField] = None
    earliest_pub_date_ms: Optional[EarliestPubDateMsField] = None
    email: Optional[EmailField] = None
    explicit_content: Optional[ExplicitField] = None
    extra: Optional[PodcastExtraField] = None
    genre_ids: Optional[GenreIdsField] = None
    id: Optional[PodcastIdField] = None
    image: Optional[ImageField] = None
    is_claimed: Optional[IsClaimedField] = None
    itunes_id: Optional[ITunesIdField] = None
    language: Optional[LanguageField] = None
    latest_episode_id: Optional[LatestEpisodeIdField] = None
    latest_pub_date_ms: Optional[LatestPubDateMsField] = None
    listen_score: Optional[ListenScoreField] = None
    listen_score_global_rank: Optional[ListenScoreGlobalRankField] = None
    listennotes_url: Optional[PodcastLNUrlField] = None
    looking_for: Optional[PodcastLookingForField] = None
    publisher: Optional[PublisherField] = None
    rss: Optional[RssField] = None
    thumbnail: Optional[ThumbnailField] = None
    title: Optional[PodcastNameField] = None
    total_episodes: Optional[TotalEpisodesField] = None
    type: Optional[PodcastTypeField] = None
    update_frequency_hours: Optional[UpdateFrequencyHoursField] = None
    website: Optional[WebsiteField] = None


class PodcastTypeaheadResult(BaseModel):
    explicit_content: Optional[ExplicitField] = None
    id: Optional[PodcastIdField] = None
    image: Optional[ImageField] = None
    publisher_highlighted: Optional[PublisherHighlightedField] = None
    publisher_original: Optional[PublisherOriginalField] = None
    thumbnail: Optional[ThumbnailField] = None
    title_highlighted: Optional[PodcastTitleHighlightedField] = None
    title_original: Optional[PodcastTitleOriginalField] = None


class SubmitPodcastResponse(BaseModel):
    podcast: PodcastMinimum
    status: Status1 = Field(
        ..., description='The status of this submission.', examples=['found']
    )


class TypeaheadResponse(BaseModel):
    genres: Optional[List[Genre]] = Field(
        None,
        description="Genre suggestions. It'll show up when the **show_genres** parameter is *1*.",
    )
    podcasts: Optional[List[PodcastTypeaheadResult]] = Field(
        None,
        description="Podcast suggestions. It'll show up when the **show_podcasts** parameter is 1.",
    )
    terms: List[str] = Field(
        ...,
        description='Search term suggestions.',
        examples=[['startup sales', 'startup', 'startups', 'star wars']],
    )


class BestPodcastsResponse(BaseModel):
    has_next: bool = Field(..., examples=[True])
    has_previous: bool
    id: int = Field(..., description='The id of this genre', examples=[95])
    listennotes_url: BestPodcastsLNUrlField
    name: str = Field(..., description="This genre's name.", examples=['Business News'])
    next_page_number: int = Field(..., examples=[3])
    page_number: int = Field(..., examples=[2])
    parent_id: int = Field(..., description='The id of parent genre.', examples=[93])
    podcasts: List[PodcastSimple]
    previous_page_number: int = Field(..., examples=[1])
    total: int = Field(..., examples=[325])


class CuratedListFull(BaseModel):
    description: Optional[CuratedDescriptionField] = None
    id: Optional[CuratedIdField] = None
    listennotes_url: Optional[CuratedLNUrlField] = None
    podcasts: Optional[List[PodcastSimple]] = Field(
        None, description='Complete meta data of all podcasts in this curated list.'
    )
    pub_date_ms: Optional[CuratedPubDateMsField] = None
    source_domain: Optional[CuratedSourceDomainField] = None
    source_url: Optional[CuratedSourceUrlField] = None
    title: Optional[CuratedNameField] = None
    total: Optional[CuratedTotalPodcastsField] = None


class CuratedListSearchResult(BaseModel):
    description_highlighted: Optional[str] = Field(
        None,
        description="Highlighted segment of this curated list's description",
        examples=[
            '...<span class="ln-search-highlight">Star</span> <span class="ln-search-highlight">Wars</span> fans in Reddit shared their favorite podcasts.'
        ],
    )
    description_original: Optional[str] = Field(
        None,
        description="Plain text of this curated list's description",
        examples=['Star Wars fans in Reddit shared their favorite podcasts.'],
    )
    id: Optional[CuratedIdField] = None
    listennotes_url: Optional[CuratedLNUrlField] = None
    podcasts: Optional[List[PodcastMinimum]] = Field(
        None, description='Up to 5 podcasts in this curated list.'
    )
    pub_date_ms: Optional[CuratedPubDateMsField] = None
    source_domain: Optional[CuratedSourceDomainField] = None
    source_url: Optional[CuratedSourceUrlField] = None
    title_highlighted: Optional[str] = Field(
        None,
        description="Highlighted segment of this curated list's title",
        examples=[
            'What are some good <span class="ln-search-highlight">Star</span> <span class="ln-search-highlight">Wars</span> Podcast to listen to?\n'
        ],
    )
    title_original: Optional[str] = Field(
        None,
        description="Plain text of this curated list's title",
        examples=['What are some good Star Wars Podcast to listen to?'],
    )
    total: Optional[CuratedTotalPodcastsField] = None


class CuratedListSimple(BaseModel):
    description: Optional[CuratedDescriptionField] = None
    id: Optional[CuratedIdField] = None
    listennotes_url: Optional[CuratedLNUrlField] = None
    podcasts: Optional[List[PodcastMinimum]] = Field(
        None, description='Minimum meta data of up to 5 podcasts in this curated list.'
    )
    pub_date_ms: Optional[CuratedPubDateMsField] = None
    source_domain: Optional[CuratedSourceDomainField] = None
    source_url: Optional[CuratedSourceUrlField] = None
    title: Optional[CuratedNameField] = None
    total: Optional[CuratedTotalPodcastsField] = None


class EpisodeFull(BaseModel):
    audio: Optional[AudioField] = None
    audio_length_sec: Optional[AudioLengthSecField] = None
    description: Optional[EpisodeDescriptionField] = None
    explicit_content: Optional[ExplicitField] = None
    id: Optional[EpisodeIdField] = None
    image: Optional[EpisodeImageField] = None
    link: Optional[LinkField] = None
    listennotes_edit_url: Optional[EpisodeLNEditUrlField] = None
    listennotes_url: Optional[EpisodeLNUrlField] = None
    maybe_audio_invalid: Optional[MaybeAudioInvalidField] = None
    podcast: Optional[PodcastSimple] = None
    pub_date_ms: Optional[EpisodePubDateMsField] = None
    thumbnail: Optional[EpisodeThumbnailField] = None
    title: Optional[EpisodeNameField] = None
    transcript: Optional[TranscriptField] = None


class EpisodeSimple(BaseModel):
    audio: Optional[AudioField] = None
    audio_length_sec: Optional[AudioLengthSecField] = None
    description: Optional[EpisodeDescriptionField] = None
    explicit_content: Optional[ExplicitField] = None
    id: Optional[EpisodeIdField] = None
    image: Optional[EpisodeImageField] = None
    link: Optional[LinkField] = None
    listennotes_edit_url: Optional[EpisodeLNEditUrlField] = None
    listennotes_url: Optional[EpisodeLNUrlField] = None
    maybe_audio_invalid: Optional[MaybeAudioInvalidField] = None
    podcast: Optional[PodcastMinimum] = None
    pub_date_ms: Optional[EpisodePubDateMsField] = None
    thumbnail: Optional[EpisodeThumbnailField] = None
    title: Optional[EpisodeNameField] = None


class GetCuratedPodcastsResponse(BaseModel):
    curated_lists: List[CuratedListSimple]
    has_next: bool = Field(..., examples=[True])
    has_previous: bool = Field(..., examples=[True])
    next_page_number: int = Field(..., examples=[3])
    page_number: int = Field(..., examples=[2])
    previous_page_number: int = Field(..., examples=[1])
    total: int = Field(..., examples=[25])


class GetEpisodeRecommendationsResponse(BaseModel):
    recommendations: List[EpisodeSimple]


class GetEpisodesInBatchResponse(BaseModel):
    episodes: List[EpisodeSimple]


class GetPodcastRecommendationsResponse(BaseModel):
    recommendations: List[PodcastSimple]


class GetPodcastsInBatchResponse(BaseModel):
    latest_episodes: Optional[List[EpisodeSimple]] = Field(
        None,
        description='Up to 10 latest episodes from these podcasts, sorted by **pub_date**. This field shows up only when **show_latest_episodes** is 1.\n',
    )
    podcasts: List[PodcastSimple]


class PlaylistItem(BaseModel):
    added_at_ms: Optional[int] = Field(
        None,
        description='Timestamp (in milliseconds) when this item is added.',
        examples=[1595567004958],
    )
    data: Optional[Union[EpisodeSimple, PodcastSimple, CustomAudio, DeletedItem]] = None
    id: Optional[int] = Field(None, description='Playlist item id.', examples=[23])
    notes: Optional[str] = Field(
        None, description='Notes for this item.', examples=['This is a good episode.']
    )
    type: Optional[Type] = Field(
        None,
        description="The type of this playlist item.\nIf a playlist is **episode_list**, then an item could be either **episode** or **custom_audio**.\nIf it's **podcast_list**, then an item can only be **podcast**.\n",
        examples=['episode'],
    )


class PlaylistResponse(BaseModel):
    description: Optional[PlaylistDescriptionField] = None
    id: Optional[PlaylistIdField] = None
    image: Optional[PlaylistImageField] = None
    items: Optional[List[PlaylistItem]] = Field(
        None, description='A list of playlist items.'
    )
    last_timestamp_ms: Optional[PlaylistLastTimestampMsField] = None
    listennotes_url: Optional[PlaylistListennotesUrlField] = None
    name: Optional[PlaylistNameField] = None
    thumbnail: Optional[PlaylistThumbnailField] = None
    total: Optional[int] = Field(
        None, description='Total number of items in this playlist.', examples=[325]
    )
    total_audio_length_sec: Optional[int] = Field(
        None,
        description='Total audio length of all episodes in this playlist, in seconds. It will have a valid value only when type is **episode_list**. In other words, it will be 0 if type is **podcast_list**.',
        examples=[234567],
    )
    type: Optional[Type1] = Field(
        None,
        description='The type of this playlist, which should be either **episode_list** or **podcast_list**.\n',
        examples=['episode_list'],
    )
    visibility: Optional[PlaylistVisibilityField] = None


class SearchResponse(BaseModel):
    count: Optional[int] = Field(
        None, description='The number of search results in this page.', examples=[10]
    )
    next_offset: Optional[int] = Field(
        None,
        description='Pass this value to the **offset** parameter to do pagination of search results.',
        examples=[10],
    )
    results: Optional[
        List[Union[EpisodeSearchResult, PodcastSearchResult, CuratedListSearchResult]]
    ] = Field(None, description='A list of search results.')
    took: Optional[float] = Field(
        None,
        description='The time it took to fetch these search results. In seconds.',
        examples=[0.093],
    )
    total: Optional[int] = Field(
        None, description='The total number of search results.', examples=[1989]
    )
